_core:
  default_config_hash: 1TswGK46jyu77aIM7Z-0JVQs5bxHmo-gtgrvrQGMXxc
favicon:
  path: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: false
logo:
  path: 'public://pexels-chanwalrus-941861.jpg'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#1b9ae4'
